### ISSUE TITLE
Security issue? Orders viewable by everyone.

### ISSUE THREAD

**Issue by rmoriz** [armandofox/audience1st#1]
Hi,

orders are publicy viewable, not tied to a user object/session, e.g.

https://www.audience1st.com/altarena/orders/1121
https://www.audience1st.com/altarena/orders/3121

**Comment by armandofox** [comment]
that's weird, there is a before_filter on it.  thanks for the heads up.

Armando Fox
Professor, Computer Science Division
Faculty Advisor, UC Berkeley MOOCLab
fox .at. cs .dot. berkeley .dot. edu
581 Soda Hall MC#1776, Berkeley, CA 94720-1776
+1.510.642.6820 / http://www.cs.berkeley.edu/~fox

TAKE MY CLASS FOR FREE VIA edX:  http://saas-class.org  
LIKE IT ON FACEBOOK:  http://facebook.com/saas-class
TRY MY BOOK (NOT FREE): http://beta.saasbook.info (goes with the course)
