### ISSUE TITLE
"Email address already exists" error message links to a broken login page

### ISSUE THREAD

**Issue by aetherknight** [armandofox/audience1st#2]
On the hosted www.audience1st.com website, if I have previously created an account and try to create a new one, I see a flash message that indicates I can log in with my existing account. However, when I click the link, I get a 404:

<img width="778" alt="user_exists_flash_login_link" src="https://user-images.githubusercontent.com/62613/27006037-cdf49d16-4ddf-11e7-86ca-0fb1c05752cb.png">

<img width="532" alt="login_link_result" src="https://user-images.githubusercontent.com/62613/27006039-dcdb8c7c-4ddf-11e7-9561-0f9cb4bce5ff.png">

**Comment by armandofox** [comment]
Fixed in 26e75c
