### ISSUE TITLE
Error message in the form escapes template HTML

### ISSUE THREAD

**Issue by aetherknight** [armandofox/audience1st#3]
<img width="783" alt="user_exists_flash" src="https://user-images.githubusercontent.com/62613/27006062-4d32b25c-4de0-11e7-95ea-938be88bfc2a.png">

The error message down by the form contains HTML content that is escaped. This is probably due to escaping all error message text in order to prevent Cross-Site Scripting (XSS).

Also of note: the same error text shows up in the green flash message, where it renders as HTML instead of being escaped.

**Comment by armandofox** [comment]
Fixed in b82bcbb
